title: # Name of your blog (this will show up at the top of your page and in the RSS feed)
  Adrien Joly

author: # Your name, as you want it to appear underneath each post and in the footer
  Adrien Joly

avatar: # URL of your avatar or profile pic (you could use your GitHub profile pic)
  /img/photo.jpg

description:
  Adrien Joly is a full stack software engineer, tech lead, teacher, drummer. This is my homepage.

keywords: javascript,hacker,prototyping,startup,paris,software,development,programming,whyd,openwhyd,innovation,node.js,music,drums,drummer,batteur,minab,fhacktory,hackathon,man is not a bird,harissa

repository: adrienjoly/adrienjoly.github.com

google_analytics: UA-1858235-4

twitter: # used by the jekyll seo plugin
  username: adrienjoly
  card: summary

social:
  name: Adrien Joly
  links:
    - https://twitter.com/adrienjoly
    - https://www.linkedin.com/in/adrienjoly
    - https://github.com/adrienjoly
    - https://medium.com/@adrienjoly

defaults:
  - scope:
      path: ""
    values:
      image: "/img/photo.jpg"
      author: "@adrienjoly"

# github defaults
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# additional config
exclude:
  - node_modules
  - "**/node_modules"
  - Gemfile
  - Gemfile.lock
  - src
  - tmp/
  - vendor/

plugins:
  - jekyll-seo-tag
